### ISSUE TITLE
Scorer does not work with new portaspeech version

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#100]
Hi,

run_scorer does not work with new portaspeech version because of Tensor expected but Tuple provided on line 135 of Scorer 
https://github.com/DigitalPhonetics/IMS-Toucan/blob/48fc098ff09fffd9917e6b8ce3ca94778bc76ce0/Utility/Scorer.py#L135

I am trying to understand with the run_scorer (that needs adaptation regarding its argument name to adapt to portaspeech instead of fastspeech) why my initial dataset composed of 98 samples has only 88 files analyzed and finally only 73 datapoints. So why is it loosing 20% of the dataset ?

**Comment by Flux9665** [comment]
Right, I kind of overlooked the scorer when I adapted to the new architecture. I will make a fix soon. The loss calculation is handled differently, the losses are now summed up outside of the model rather than inside the forward method, so that logging them is easier. 

If you have only 100 samples though, I would recommend to listen to all of them manually though. For 100 samples, that should be doable in just a few minutes, so you can check if there is a word missing in the audio that is in the text or a wors is mispronounced etc. and then fix the sample directly, rather than removing it heuristically.

**Comment by Ca-ressemble-a-du-fake** [comment]
Oh then that's weird because those samples should be perfect. I will listen to them again though and keep you posted of they all match their transcription although the scorer removes some of them.

**Comment by Flux9665** [comment]
Current version now uses the scorer with the new architecture and works in my testing.
