### ISSUE TITLE
How to prevent mispronunciation when finetuning ? 

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#101]
Hi,

I am fine tuning the meta model for French with a 3 minute dataset. But the finetuned model quickly starts to mispronounce words (when meta does not).

What does this phenomenon show ? And how to prevent it (are there parametersto freeze some model layers) ? I thought finetuning would not degrade the pretrained model so quickly. 

I will try and add examples when I am back to keyboard.

Thanks in advance for your help,

**Comment by Ca-ressemble-a-du-fake** [comment]
Correct me if I'm wrong but this phenomenon (mispronunciation in the fine tuned model whereas the pretrained model was ok) is called overfitting. This is due to over training.

It would make sense because in "Language-Agnostic Meta-Learning for Low-Resource
Text-to-Speech with Articulatory Features" the authors trained with 30 minutes and noticed overfitting from 80k steps. Here with 3 minutes overfitting is bound to appear from 8k steps. Condequently at 20k steps the distortions are present.

On the contrary limitting the finetuning to 1000 steps per minute of dataset (here 3k steps) does not bring these distortions and result is stunning.

So far I could not hear any noticeable difference between training 3k steps with only cycle 1, or only cycle 2, or 1500 steps of both cycles. I thought doing cycle 2 objectives would only transfer the target's embeddings but it does not seem to be the case.

**Comment by Flux9665** [comment]
Exactly, 3 minutes of data is too little data to finetune on its own for many steps. You run into a problem called catastrohpic forgetting, which means that the model learns to reconstruct the 3 minutes perfectly, but forgets everything else, because it no longer needs those old skills.

This can be fixed by merging your 3 minutes of data with a bigger clean multispeaker dataset, if one is available. Or just training fewer steps.

The phase 1 and 2 are mostly important during the pretraining to get better speaker similarity in multispeaker models. For finetuning, the phase 2 should be irrelevant. I'll adapt the finetuning example script to not use phase 2 in the future.

**Comment by Ca-ressemble-a-du-fake** [comment]
Great thanks, I know what I have to do now : only fine tune for 45 minutes (3k steps). 

But wait can I merge all my short datasets into a bigger one, fine tune Meta model on this bigger dataset ? And then how can I select a given speaker ? 

For clarity sake I opened a specific question on that topic. Please see [here for details](https://github.com/DigitalPhonetics/IMS-Toucan/issues/105).

**Comment by Flux9665** [comment]
Yes, you can merge all your datasets and train the meta model on the bigger one. If the amount of data per speaker is highly unballanced however, the model will likely learn the voice of the speakers with the most data significantly better than the ones with little data. If you want the model to also learn the voice of the speakers with only a few minutes, then you should probably train a dedicated model just for that. To select the voice of the TTS at inference time, pass a reference audio as the speaker_reference argument.

**Comment by Ca-ressemble-a-du-fake** [comment]
That makes perfectly sense, thank you. Gonna try this again carefuly.
