### ISSUE TITLE
How to change accent of French pretrained model to make it sound more like French spoken in France (Paris)

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#109]
Hi,

As noticed in https://github.com/DigitalPhonetics/IMS-Toucan/issues/74 French model makes pronunciation mistakes with regards to the language spoken in France. So "dessin" (drawing) is said like "décès" (death), "chemin" is sometimes pronounced like "ch'min" (middle "e" is kind of swallowed). There may be other differences, these are just examples.

Overall it still does not sound like French from France and to me this is noticeable. Is there a way to change tweak the accent of the pretrained model to match the accent from Fr-Fr ? What would be my best option (I could release the model if I don't have to also release the private datasets) ?

1) Fine tune the pretrained model on my 25 hour dataset (4 speakers, 2M/2F)  ~ 25k samples
2) Train the model from scratch with this 25 hour dataset 
3) Something else ?

Although my hardware is limited compared to yours (GPU with 24 GB), I could already train [YourTTS](https://github.com/coqui-ai/tts) model from scratch and it could speak correctly after one day of training.

If I do the math with a batch size of 16 each epoch requires around 1500 steps. During training it shows 1,7 iterations /  s so it will make 1/4 of an hour per epoch => 4 epochs / hour => ~ 100 epochs / day.

So will 100 epochs (1 day of training) be sufficient to have the speak French from France ?

Do I have to do stage 1 or also stage 2 (you wrote previously that stage 2 objectives were not recommended for finetuning, but here I want to change the accent so it may make sense) like 80k for stage 1 and 20k for stage 2 ?

How long did you train Meta model for (in time and steps if possible to have a metrics) ?

Thank you in advance for your advice :smile:

**Comment by Ca-ressemble-a-du-fake** [comment]
Eventually I changed the batch size to 32 because there was room for it on the GPU (I am using 16kHz mono audio so it uses around 18GB of VRAM). So it sped a bit the training up.

Before the training it was like this ("Je ne te fais pas un dessin" <=> "pa bəzwˈɛ də vu fˈɛʁ œ dɛsˈɛ.") :

https://user-images.githubusercontent.com/91517923/225868804-adb4360b-d6cf-4c8b-944a-3befec78b3de.mp4

As you can hear "dessin" is pronounced "décès".

After around 12 hours it is now producing French from France :

https://user-images.githubusercontent.com/91517923/225869386-bda15336-8fd8-4774-bfd8-2e9fa7285229.mp4

Yet it bring new flaws (that can be corrected by writing words differently as with any other tts) but overall it sounds much closer to French spoken in France.

With the sole exception of the word "sein" (breast) which Toucan does not want to pronounce correctly (whereas the original Meta did it perfectly). No matter how I write it says "sé" : 

`
Now synthesizing: Le sein, le sien, le mien, le tiens
Phonemes:

~lə sˈɛ~ lə sjˈɛ~ lə mjˈɛ~ lə tjˈɛ~#
`, does not get properly pronounced although it is said correctly in the datasets (36 times overall).

Original meta (fr-ca) : 

https://user-images.githubusercontent.com/91517923/225884710-d07f5302-64fe-419b-b424-d163cdb3bd4e.mp4

With fine tuned model (fr-fr) : 

https://user-images.githubusercontent.com/91517923/225884891-5d44388d-3f08-427e-b999-1e9b0a6efccf.mp4


Maybe cycle 2 objectives will correct this (I will soon be able to answer this question  :wink:)

As a conclusion the fine tuning of Meta model to change the accent in French was not painful at all and showed the expected results very quickly :smile:.

**Comment by Ca-ressemble-a-du-fake** [comment]
That's really weird : To remedy the problem with "sein" pronounced like "sé" I tried to train the model from scratch based only on siwis (that is present in the transcript dicts). But the problem remains exactly the same although the rest is correct after only 13k steps. So siwiss dataset may be the cause of this incorrect pronunciation because "dessin" is also wrongly pronounced "décès".

I tried with my dataset and the model (after 48k steps) struggles with "patin" (skate) that is pronounced like "paté", ["gratin"](https://en.wiktionary.org/wiki/gratin#French) pronounced like "graté" (scratched), and still with "sein" that is pronounced "sé".

So overall it has a problem with the nasal "ɛ̃". Why is it ? Can it be that there is a flaw somewhere else ?

The phonemizer seems to properly handle this phoneme :
```
espeak-ng -vfr-fr --ipa -w sein.wav "sein"

sˈɛ̃
```

Will training longer solve the issue ?

**Comment by Ca-ressemble-a-du-fake** [comment]
Disclaimer : I knew nothing about IPA! Now I've learned that "ɛ̃" and "ɛ" are different phonemes! So this may give an explanation.

Actually I noticed that when espeak produced a "ɛ̃" in the command line, Toucan produced "ɛ". So this may be the root cause of the problem (`postprocess_phoneme_string` filters this "ɛ̃").

If I try to use phonemes as input and give "sɛ̃" I get an error because of unknown phoneme.

```
Now synthesizing: sɛ̃
Phonemes:
sɛ̃   

unknown phoneme: ̃

```

THe problem remains if I add the "ɛ̃" in articulatory_features, train the model from scratch and then run the inference against this model. So somewhere else espeak output must be modified.

~By the way even when espeak-ng is uninstalled system-wise (apt remove) Toucan keeps working. So the version used by EspeakBackend may be different from the one run in CLI.~ (espeakbackend only needs espeak library .so).

**Comment by Flux9665** [comment]
Lots of interesting observarions in this thread, thank you for sharing! I'll try to reply to everything you said in order:

With your data I would train from scratch. It won't be good for voice-changing if it has only seen 4 different speakers, but 25 hours is more than enough to train from scratch and then you can be sure that the accent will match the data. If you need the voice-changing abilities to mimic unseen speakers, I'd go with finetuning or mixing your data with multispeaker French data that has a lot more speakers (but that's hard to find without accents).

Regarding phase 1 and phase 2: the next release will remove the phase 2 completely and only use phase 1. If we want to do better voice cloning in the future we'll think about this setup again. But for now, multilinguality is the focus and for that, the scond phase is causing more problems than it's helping. So I recommend setting phase 2 steps to 0 and stopping the training before the step count exceeds phase 1. Accent should not be impacted by phase 2, only the voice of the speaker.

The meta model was trained for 100,000 steps, which took about 28 hours. I'm still looking for ways to make this quicker, but overall I'm already pretty happy with training times just over a day for a model that is really thoroughly trained. Good results can already be achieved after ~4 hours usually, so for testing I run much smaller step numbers (around 20k with the newest experimental setup).

I would like for our model to speak French from France, the problem is that I unfortunately chose to learn Spanish in school, so I know basically nothing about the French language and I cannot distinguish between France-French and Canada-French. It seems the majority of multilingual librispeech French is Canadian French, which is the biggest portion of the French data we are using. My colleagues and I spent some time recently to filter some portions of our data heuristically to exclude speakers from librivox which are likely not from France (e.g. they read more audiobooks in English than in French on LibriVox).

We are also working on the French text-processing. I believe there might be a small error in the phonemizer, with the ```ɛ̃```. Maybe a unicode character is used that looks very very similar, but is not actually the same character. The phonemizer sees the tilde as a separate character from the ```ɛ```. I remember seeing this and thinking it's just a bug and removing the special character in ```TextFrontend.py```. But now that you mention this, I will look into this again. There is definitely a bug somewhere that should be fixed. I'll update once I find it

**Comment by Flux9665** [comment]
should be fixed, it was mostly a legacy problem from the days when we used lookup table based phonemes. Now that we use features, we can edit the nasal feature if we encounter a nasalization tilde easily, so I added this. There are more unsupported IPA symbols which I need to take care of in the future, but I hope at least French should now be covered.

**Comment by Ca-ressemble-a-du-fake** [comment]
Awesome :+1: ! Thanks for fixing this so quickly and answering to my points! That seems to be solved. Now the Meta model sounds to me correct (as a native French speaker from metropolitan France). Maybe @tomschelsen can confirm this but to me there is no need to further filter the French dataset as it now sounds as Metropolitan French (from Paris, the one that you can hear on national TV / radios).

I am surprised there is no need to retrain the model from scratch after your adding the nasal vowel. How can ɛ̃ now be spoken correctly during inference whereas this sign did not exist during training (because you added it after you trained the initial meta model) ?

**Comment by Flux9665** [comment]
Not needing to retrain the model is indeed very cool :) That's one of the massive advantages of using articulatory feature representations rather than identities of phonemes. We can zero-shot unseen phonemes, purely based on their properties. Exactly this is what's happening with the meta model: It has never been trained to produce nasal vowels, but it can approximate them. When actually training with this, the quality will get even better. (You'd have to re-extract the dataset cache file for this though.)

**Comment by Ca-ressemble-a-du-fake** [comment]
That's pretty cool indeed! So now I have some readings namely your paper about it. This [one](https://arxiv.org/abs/2203.03191) should help me better understand what's all about, or you'd advise another one ?

**Comment by Flux9665** [comment]
Yes, that's the paper where we introduce these features that allow approximating unseen phonemes :)

We participated in a challenge that ended two days ago on French TTS, here's a demo of our system, in case you're interested:
https://huggingface.co/spaces/Flux9665/Blizzard2023IMS

This one was properly trained with the nasal vowels and does no longer zero shot them. The next release will include a new meta model that should be significantly better at French.

**Comment by Ca-ressemble-a-du-fake** [comment]
Looking forward to finetuning this new model then👍 ! The demo with the tongue twister sounds good !
