### ISSUE TITLE
Shouldn't we speak in training epochs instead of training steps ?

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#113]
Hi,

I a previous post you wrote that meta model was trained for 100k steps. But to reproduce this training experiment, wouldn't it make sense to talk in terms of training epochs ?

Because what matters is the number each dataset has been thoroughly  seen during training, doesn't it ?

I ask this question because I want to know how feasible it is to train a model from scratch for each voice I want to clone (to see if it is more accurate in terms of voice similarity than fine tuning from Meta). So my theory is that if you trained Meta for X epochs with a batch size of 32, I could get the same results with my reduced dataset for X epochs too. 

Thanks in advance for shedding lights on that topic :smile:

**Comment by Flux9665** [comment]
For classification tasks measuring things in epochs makes sense, but for generative tasks not so much. In TTS you will in most places see the number of batches trained as the measure. This is because in theory you could have endless data and show each sample to the model only once. So you could finish training before you even finished the first epoch if your dataset is large enough. 

Also especially for the Meta model, it is trained on a large number of datasets, which have all different sizes. So there is not really an epoch in this context, because we always mix languages to equal parts in all batches. After 10000 steps you might have seen 3 epochs worth of Greek, 1 epoch worth of English, 8 epochs worth of Polish and 2 epochs worth of German. 

So comparing models by the number of batches run is the best strategy I would say.

**Comment by Ca-ressemble-a-du-fake** [comment]
Ok got it, now that's clear :smile: ! Thank you!
