### ISSUE TITLE
ModuleNotFoundError: No module named 'TrainingInterfaces'

### ISSUE THREAD

**Issue by thoraxe** [DigitalPhonetics/IMS-Toucan#116]
Trying to run the fine-tuning example from the README.

```
Traceback (most recent call last):
  File "/home/thoraxe/Red_Hat/openshift/voice-cloning/IMS-Toucan/TrainingInterfaces/TrainingPipelines/finetuning_example.py", line 13, in <module>
    from TrainingInterfaces.Text_to_Spectrogram.PortaSpeech.PortaSpeech import PortaSpeech
ModuleNotFoundError: No module named 'TrainingInterfaces'
```

Steps to get here:
1) install python 3.10.9 in a virtual environment
2) pip install the requirements.txt
3) run_model_downloader.py
4) finetuning_example.py

Expected behavior: Finetuning runs

**Comment by Ca-ressemble-a-du-fake** [comment]
Hi @thoraxe, you don't run `finetuning_example.py` directly. You've got to create a handle (ie a meaningful shortcut name) for it in `run_training_pipeline.py` and then you call `run_training` and provide the gpu to use (otherwise it won't work). 

Useful excerpt from guide :

> Once this is done, we are almost done, now we just need to make it available to the run_training_pipeline.py file in the top level. In said file, import the run function from the pipeline you just created and give it a meaningful name. Now in the pipeline_dict, add your imported function as value and use as key a shorthand that makes sense.

So in your case you'd run : `python3 run_training_pipeline.py fine_ex --gpu_id 0`

Did you try that ?

**Comment by thoraxe** [comment]
Thanks. Tried this, also failed, but with a different issue.
