### ISSUE TITLE
Why is bigvgan better than Avovodo ?

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#143]
Hi,

I finetune Toucan Meta model on 1k on a reduced dataset to understand the difference between Avocodo and BigVGan. 

Here are the spectrograms :

![image](https://user-images.githubusercontent.com/91517923/234183239-b05a2324-016c-41f5-9d5e-50f0234cc30a.png)

Apart from the 12kHz area which is a bit larger for the BigVGan version I can barely differences (I may not look at the right place). Where are the improvements ?

By the way why is there a dark strip around 12kHz ?

Thanks in advance for your explanations!

**Comment by Flux9665** [comment]
You cannot see the difference in the spectrogram, because a spectrogram does not contain the phase shift information, which is what the vocoder tries to reconstruct. Since the input to the vocoder is already spectrogram, the spectrogram of the output will simply be again the same as the input ideally. 

The improvement lies in the generator of BigVGAN, which has mechanisms built in to avoid aliasing during the upsampling process.

The area at 12kHz is due to the signal being 24kHz. So anything above the Nyquist frequency (half the sampling rate, i.e. 12kHz in this case) in a spectrogram is due to a problem called _imaging_ and something that we want to avoid.

**Comment by Ca-ressemble-a-du-fake** [comment]
Thanks for your explanations. I tried to simply filter anything above 12 kHz but it did not sound better.
