### ISSUE TITLE
What'are the goals of the different branches ?

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#153]
Hi, 

I hope you're doing fine. 

I see you are working on different experimental branches of your project and not on the default one anymore. Does this mean the default one has reached its target objectives (what are/were those objectives because for eg you wrote once that stage 2 steps would be removed but could be included again if needed)? It is not that easy to understand where the project goes by looking at the code change history. 

Would you mind explaining what these new branches are supposed to do and whether the latest Toucan is worth it as far as voice cloning is concerned? I stick to v2-4 and would not mind upgrading if it solves the issues I can't explain (eg some mispronunciations whereas voice similarity is good). 

By the way, do you still need feedback (there has not been much  activity on the "issue" channel for weeks)? 

Looking forward to reading your reply as always, and wish you a pleasant summer,

**Comment by Flux9665** [comment]
Hi,

sorry for the long response times recently, I am very busy with lots of different things at the moment, so I focus on working quietly and efficient. The main branch is stable right now and in the experimental branches I'm doing experiments on different things that are highly unstable and unfinished. Once I find a solution that works well, the experimental branch will turn into the new main branch with the next release. I don't know yet when that will be, because it doesn't work yet and I have been trying many many things already.

Originally I wanted to increase the zero-shot voice cloning capabilities in the experimental branch by using a different embedding function and some tricks, but now I switched to a different strategy, because I heard that data scale might be the key. In order to scale up the amount of data used for pretraining models that can then be efficiently finetuned or simply used zero-shot, I'm now trying to make synthesis work over neural audio codecs instead of spectrograms. So far the results are very bad, the model can speak, but it sounds horrible. I have a clear vision of what I want to achieve, I just don't know yet how the model / training procedure have to change to make it work.

For now, it's probably best to stick with version 2.4 until the new stuff works properly.

**Comment by Ca-ressemble-a-du-fake** [comment]
Thanks for your answer, I was just notified today you replied last week ! I saw some articles about neural audio codecs but didn't pay attention to them because I thought they were just audio codecs ! I will read them now ! What makes you think they can be used instead of spectrograms, do you have specific papers in mind about that ?

**Comment by Flux9665** [comment]
I found this one very impressive: https://arxiv.org/abs/2302.04215

I just don't like the autoregressiveness, because that makes it much harder to control and it can cause mistakes in the speech. It's very hard to do this without autoregressiveness though, I'm struggling with that a lot. Basically, when predicting all at once in parallel, there's too little variance in the discrete outputs produced. Intelligible speech is produced, but it sounds like a robot from an early 80s movie.
