### ISSUE TITLE
Error : could not find version that satisfies the requirement

### ISSUE THREAD

**Issue by ajdsouz** [DigitalPhonetics/IMS-Toucan#26]
I tried to create a conda environment by by running the commands provided in the readme, byt faced this error. Please help solve this
![toucan error](https://user-images.githubusercontent.com/91375589/166465842-14776ba5-527d-424b-b89b-2853d4ffce5b.png)

.

**Comment by Flux9665** [comment]
It seems you haven't navigated into your clone of the toolkit. This causes the first error of the requirements.txt file not being there.

For the second error, follow https://pytorch.org/get-started/previous-versions/#v190 

What is in the readme works on my machine, I just tested it again. But just to be safe I will put this link into the readme rather than the command itself.
