### ISSUE TITLE
Question: CTC loss?

### ISSUE THREAD

**Issue by michael-conrad** [DigitalPhonetics/IMS-Toucan#28]
What is CTC loss? I have figured out that a large percentage of my `chr` samples are getting culled because of it. My samples are normalized. How negative would be the effect if I turned CTC loss checking off?

I really noticed this when I created "augmented" data where I'm combining random samples together as joined sentences (with 350 ms pauses) into 20 sec segments. I think that the fact that most of my data is single word utterances is causing an issue where certain phoneme combinations lose their correctness after 15,000 to 20,000 iterations. `Uguku` becomes `Uguk`. And `Sihgwa` becomes `S sihgwa`. So I'm trying to create synthetically augmented data to try and reduce this issue.

**Comment by Flux9665** [comment]
The CTC loss function can be used to teach a model to align two sequences without having explicit alignment information. Here's a very short but good explanation: https://paperswithcode.com/method/ctc-loss 

For the datasets, the assumption is that in large datasets there are always a couple of samples where the text and the audio don't match perfectly. So we just remove samples where the aligner has an unusually high loss when trying to perform the alignment. For small datasets it totally makes sense to turn this off. I'm implementing the scorer functionality that we talked about in another issue right now, for smaller datasets it will make more sense to look at the alignment scorer rather than to just remove them heuristically.

**Comment by Flux9665** [comment]
Scorer is included in today's release. For small datasets it makes sense to inspect them with the scorer and if there are no problematic samples in there, disabling the heuristic exclusion of bad samples during dataset creation.
