### ISSUE TITLE
Utterance cloner unable to generate speech using text different from the reference-transcription

### ISSUE THREAD

**Issue by zeinsh** [DigitalPhonetics/IMS-Toucan#33]
Hello!

I read the paper "Prosody Cloning in Zero-Shot Multispeaker Text-to-Speech" and I ran the code using "[run_utterance_cloner.py](https://github.com/DigitalPhonetics/IMS-Toucan/blob/Multi_Language_Multi_Speaker/run_utterance_cloner.py)"

Looking at the aligner between text and reference, the model is not able to generate speech using text that doesn't correspond to the reference.

However, in [your demo on HuggingFace ](https://huggingface.co/spaces/Flux9665/SpeechCloning).. this feature was supported.

Could you, please, describe how to generate a speech of different text using this approach?

**Comment by Flux9665** [comment]
Hi! 

Thanks for your interest! As you said, there always needs to be a corresponding reference utterance. In the huggingface demo, there are just multiple references, one for each prompt. At the time when I made the demo, Gradio didn't yet offer the feature to display the audios prior to executing the demo, so the references are always displayed alongside the generated audio. 

The use of this is mostly meant for privacy. So the input utterance and the output utterance are always the same and retain the original prosody, but the voice can be exchanged, so that the original speaker can remain anonymous.

**Comment by zeinsh** [comment]
Interesting! thank you for the explanation. Interesting paper.
