### ISSUE TITLE
Training process stuck at AlignerDataset.py

### ISSUE THREAD

**Issue by saibharani** [DigitalPhonetics/IMS-Toucan#34]
Hi I am trying to fine-tune the Fastspeech2 model with a custom dataset and followed all the steps according to the instructions in Readme file. But when I try to run the training the training process is stuck at AlignerDataset.py file with the following log

`Preparing`
`... building dataset cache ... `
 `32%|███████████████████████████████████████████████████▉                                                                                                                                       
            | 23/73 [00:15<00:22,  2.25it/s]`

can you give any pointers about where I might have done wrong. 

Thanks

**Comment by Flux9665** [comment]
Hi! The log looks all good, that is how it should look like. There are no indicators to why it might be stuck. If you redirect the outputs to a file, do you also redirect std:err? Without an error message I can't tell you much unfortunately. 

Since the loading runs multiprocessed it's also not that simple to find out which file is causing the problems. What you could do to debug is printing the path at this point:

https://github.com/DigitalPhonetics/IMS-Toucan/blob/941f08547af64fb02f9acfb0b0658f98d76a8b22/TrainingInterfaces/Text_to_Spectrogram/AutoAligner/AlignerDataset.py#L126

And set the amount of processes to 1 here:

https://github.com/DigitalPhonetics/IMS-Toucan/blob/941f08547af64fb02f9acfb0b0658f98d76a8b22/TrainingInterfaces/Text_to_Spectrogram/AutoAligner/AlignerDataset.py#L24

Then you will be told at which file the program encounters a problem and you can inspect the file. It should at least print an error-message though. Maybe your machine runs out of RAM?

**Comment by saibharani** [comment]
I traced back the error to espeak-ng, It is not able to phonemize few words example 'నిర్వహించారు' is a Telugu word which espeak-ng is not able to generate, the process simply gets stuck utilizing 100% CPU forever without any output. My current version is espeak 1.49 default version for Ubuntu 18.04. I am trying to compile espeak 1.51 for Ubuntu 18.04 and I will report back the output here. If you can suggest any better alternatives I will try them too.

Thanks

**Comment by saibharani** [comment]
Recompiling espeak solved the issue but now I am facing a new issue 
`File "/home/bharani/Desktop/ML/ims-toucan/TrainingInterfaces/Text_to_Spectrogram/AutoAligner/autoaligner_train_loop.py", line 73, in train_loop
    tiny_tts.load_state_dict(check_dict["tts_model"])
KeyError: 'tts_model'`

The new release of aligner.pt file has only `dict_keys(['asr_model'])` but the old 2.1 release has `dict_keys(['asr_model', 'optimizer', 'tts_model', 'tts_optimizer', 'step_counter'])` I think this is the main reason for the above error. Can you please check it once.

Thanks

**Comment by Flux9665** [comment]
Good to hear that you could trace it back to espeak-ng and even better that you were able to fix it by recompiling, thank you for reporting that! 

There are some phonemizer alternatives that I want to try out as alternatives to espeak-ng, namely epitran (https://github.com/dmort27/epitran), Charsiu (https://github.com/lingjzhu/CharsiuG2P) and transphone (https://github.com/xinjli/transphone) once the transphone code and models are released. There are some other things that I am working on first however and right now I'm pretty overloaded anyways, a lot is happening all at once, which is also why I'm very slow to respond at the moment.

The uploaded aligner.pt model should contain the tts_model for the reconstruction loss. I just downloaded it from the release, loaded it and checked its contents, for me everything is there, including the tts_model weights. Maybe you have overwritten it locally after you downloaded?
