### ISSUE TITLE
beginner guide/tutorial

### ISSUE THREAD

**Issue by A-d-DASARE** [DigitalPhonetics/IMS-Toucan#38]
Hi, Thanks for the amazing toolkit, for beginner who is dealing with low resource languages other than English, TRANSFER LEARNING from pretrained LJ speech or any other model, can we have steps/instructions from scratch?! That would be highly appreciated, thanks in advance.

**Comment by Flux9665** [comment]
Hi! The README is supposed to be just that, a beginner friendly guide for how to do everything. The meta learning checkpoint that is provided is trained on 15 languages and thousands of speaker and is very useful for finetuning to a new language. A lot has changed since I originally wrote the README file, so I might rewrite it soon so it's more up to date with the finetuning. There is a pipeline to finetune a model on a new language in an experimental branch, that will become part of the main branch in the future: 

https://github.com/DigitalPhonetics/IMS-Toucan/blob/d19ec1b22d55f889c39c2f10efa37abafc9cb192/TrainingInterfaces/TrainingPipelines/FastSpeech2_finetuning_example.py

**Comment by A-d-DASARE** [comment]
Thank you!
