### ISSUE TITLE
espeak mistake for chinese

### ISSUE THREAD

**Issue by ease-zh** [DigitalPhonetics/IMS-Toucan#50]
Actually, this is a problem with espeak-ng's ipa output.
For mandarin Chinese, using five level tone mark, the tone mark for a character is more than one, i.e.:
1. 55 for the 1st tone, namely "阴平",
2. 35 for the 2nd tone, namely "阳平",
3. 214 for the 3rd tone, namely "上声",
4. 51 for the 4th tone, namely "去声".

When using `espeak` with language "cmn-latn-pinyin", it will output correct tonal mark, but when using `--ipa` flag, the output will only maintain the first one, which is clearly a mistake. For example: 
![result](https://user-images.githubusercontent.com/28568749/199916319-adf854cd-a329-4123-9fed-700771b1999a.png)
And in the latest `phonemizer` package (v3.2.1), it passed the ipa code to espeak api, and will always get the wrong result. By the way, I'm using the latest espeak-ng (eSpeak NG text-to-speech: 1.52-dev, build from github's source code). 

Fortunately, we can simply use the tonal mark in Pinyin instead, with just one line code  inserted to `Preprocessing/TextFrontend` before line 265, as:
```python
class ArticulatoryCombinedTextFrontend:
    ...
    def get_phone_string(...):
        ...
        if self.g2p_lang == "cmn-latn-pinyin" or self.g2p_lang == "cmn":
            phones = ' '.join([re.sub(r'[1-5ɜ]', u[-1], p)for p, u in zip(phones.split(), utt.split())])
            ...
```
![code](https://user-images.githubusercontent.com/28568749/199914621-441004b2-2544-41f4-925c-b37a20728cae.png)

**Comment by Flux9665** [comment]
Thank you for the detailed explanation of the problem and the proposed solution! 

I will update the current main branch and the most recent release accordingly. I'm also working on some changes to improve the embedding function, so I have to re-train the models anyway. I'll also update the model in the release page to one that is trained with the correct tones for Mandarin once training is done. I wonder if the problem is the same for other languages where the tone consists of multiple targets e.g. in Vietnamese, or wheter that is only the case for the pinyin version of espeak

**Comment by Flux9665** [comment]
There were a bunch of edgecases, like punctuation marks which espeak removes, but pypinyin leaves in. I wrote some handling for that, but then I decided that I don't like how hacky the solution was. Instead I looked for another way to convert pinyin to IPA and found dragonmapper (https://github.com/tsroten/dragonmapper). It is now used instead of espeak for the conversion to IPA and for some annotated example sentences I found online, it seems to work pretty well.

I also looked into how espeak works for Vietnamese, whether it has the same bug. But for Vietnamese, the numbers that espeak produces have an entirely different meaning. They denote first, second, third and so on, not the level of pitch. So for Vietnamese, espeak works as intended (although I'm not sure how good)

Anyway, the next models that I will train will contain the fix and I'm looking forward to see the impact.
