### ISSUE TITLE
What do the cycle objectives refer to ? 

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#58]
Hi,

I saw parameters called 'phase_1_steps' and 'phase_2_steps' in the finetuning pipeline. It seems to deal with 'cycle objectives' and do not appear in all pipelines. So far I set them equally so that they sum up to 200k steps but I am not sure what they actually do. 

I could not find a reference to them in the paper. How should they be set and what are their goals ?

Thank you for shedding light on that topic !

**Comment by Flux9665** [comment]
The cycle objective is part of a paper that's under review and not yet published, that's why it's not documented anywhere yet. The cycle consistency objective compares the utterance-embedding that goes into the model to an utterance-embedding that is derived from the output of the model. Ideally, the output should contain all of the information that was in the input embedding (i.e. same speaker, same emotion, same prosody etc.). So we just minimize the distance between input and output embedding. It forms a cycle, input goes to output, output goes back to input, thus the name.
