### ISSUE TITLE
Does finetuning Vocoder on generated mels work?

### ISSUE THREAD

**Issue by bharaniyv** [DigitalPhonetics/IMS-Toucan#65]
Hi,
Do you think fine-tuning the vocoder on generated mels from fs2 help improve the quality of the synthesis and possible help remove some of the artifacts? and the current fs2 model is 16K do you think increasing it to 22K help in improving quality?

Thanks

**Comment by Flux9665** [comment]
Increasing the sampling rate of the generated spectrograms increases the complexity of the task the model has to solve and its runtime requirements, but yes, with clean data it would probably sound better.

Finetuning the vocoder on TTS outputs is done frequently and is known to bring pretty good improvements for removing artifacts. However, then the vocoder becomes specialized for one certain model and loses some of it's generality. Because I want the vocoder to be universal, I don't plan on doing that and finding other solutions instead, but if you want to try it, it probably increases the quality.

**Comment by bharaniyv** [comment]
I started working on 22.05K sample rate fs2 model, currently preparing dataset in 22K and will try training new model, but I think the Vocoder will not be compatible since it is trained on 16K datasets, but what other Vocoder do you think will work with the configuration of this module, especially how we handle the Stft part since it is also very important for vocoder along with sample rate?

**Comment by Flux9665** [comment]
My implementation is based on this one: https://github.com/kan-bayashi/ParallelWaveGAN

It is uses the same spectrogram representation as in espnet: https://github.com/espnet/espnet

So any vocoder from the espnet model zoo that is trained on 22500Hz should work.
