### ISSUE TITLE
Training avocodo is brutally slow

### ISSUE THREAD

**Issue by iamkhalidbashir** [DigitalPhonetics/IMS-Toucan#78]
Traing FS2 is fine (as it uses gpu)

But training vocoder uses GPU for very short time and mostly CPU is at 100% and training is very slow for 152 audio files
In 10 minutes I reached 88 steps

![image](https://user-images.githubusercontent.com/27646811/213116021-3aef97d5-0794-4bfc-9cb6-88f5cba51be6.png)
![image](https://user-images.githubusercontent.com/27646811/213116096-d9314c1a-abe5-44a7-9239-8f697e299fea.png)
![image](https://user-images.githubusercontent.com/27646811/213115733-54b80ba7-a3d4-474f-b942-bb47b189bfc5.png)

**Comment by Flux9665** [comment]
I get around 6 iterations per second. The pretrained checkpoints are trained for over two million steps, which took about a week. It is probably due to the amount of CPU cores in your machine. The dataloader spawns as many worker processes as there are samples in a batch. So for 32 batchsize, that's 32 processes which each take up a core. I normally train on a machine with 128 CPU cores, so I never noticed that this is a problem, but for training on smaller machines that can definitely be a problem. 

https://github.com/DigitalPhonetics/IMS-Toucan/blob/257ec096e60efa12dfcae9b575dbf003c15ccb8e/TrainingInterfaces/Spectrogram_to_Wave/HiFiGAN/hifigan_train_loop.py#L64

I will change this to a much more reasonable way of setting the workers for other machines. The problem is just that there is some heavy processing happening in the dataloading because we do the trick where we input low samplingrates and output high samplingrates on random windows. This will be alleviated in the next version of the toolkit which changes the samplingrate to half of what it currently is. This will lower the theoretical upper bound for quality, but increase the quality we are actually getting. This part of the new release is already done, but other places are still stuck a bit.

**Comment by Flux9665** [comment]
This should fix it, please let me know if the training is still slow. Maybe there's another point where I rely too much on our massive in-house servers.

https://github.com/DigitalPhonetics/IMS-Toucan/blob/f0c2d9e16b4b48289709c6fe0c6c71460238f093/TrainingInterfaces/Spectrogram_to_Wave/HiFiGAN/hifigan_train_loop.py#L64

**Comment by iamkhalidbashir** [comment]
Oh okay got it. Are you available to work on this new release now a days ? Let me know if there is something for me

**Comment by Flux9665** [comment]
The next 2 weeks are busy with teaching, after that I hope to wrap it up quickly. Mostly comparing a few architecture choices and finding a potential bug, I have training runs going in the background.

**Comment by iamkhalidbashir** [comment]
Great! Looking forward to it 🎉

**Comment by bharaniyv** [comment]
I am also attempting to finetune Avocodo 48k model and I am able to get a speed of 1.1 steps per second with 3060 GPU and 6 core Ryzen 5 CPU at a batch size of 8 at this speed it might take atleast 1 week to reach reasonable quality. Are you successful in increasing your training speed?

**Comment by Flux9665** [comment]
A major point that takes a lot of time is the resampling of audio. It should totally happen in the preprocessing in the init of the Vocoder Dataset, not in the getitem, I don't know what I was thinking. In the upcoming version, this is fixed. Also dropping the sampling rate to 24kHz gives a good increase in speed as well, while the quality of the resulting audio is even better in my ears. I can now train with the new architecture pretty stable, so the release is close to being done. I'm just adding in a few more features that were requested for a long time before training the multilingual model and preparing the release.

**Comment by Flux9665** [comment]
Today's release includes fixes to make vocoder training faster on machines with fewer CPU cores. Also, a full checkpoint with discriminator is included in the release for finetuning purposes. 

Next release will update the generator architecture, NVIDIA claims their BigVGAN works even better on out of domain data than all the other stuff I tried so far, so I'll combine it all together.
