### ISSUE TITLE
Request to release Avocodo Discriminator checkpoint for finetuning

### ISSUE THREAD

**Issue by bharaniyv** [DigitalPhonetics/IMS-Toucan#81]
I am trying to finetune Avocodo model on Asian languages data and possibly control metallic sounding but it is taking way too long time since the released checkpoint has only generator but no discriminator weights in it and I have to retrain discriminator from sratch which may take atleast 1 week time to reach reasonable quality but if you can release a discriminator checkpoint for any model 48k or 24k it can help finetune faster. Can you release a checkpoint if possible.

Thanks

**Comment by bharaniyv** [comment]
my training still sounds distorted and a lot worse when compared to original version even after 350K steps I think it may be due to my low batch size of just 7 due to my low-end GPU. Is there any chance you can release a Discriminator checkpoint?

I think the finetuning will be easier with a checkpoint than from sratch.

Thanks

**Comment by Flux9665** [comment]
Here I uploaded the final checkpoint of my training of the 24kHz vocoder. It includes the full state dicts, so it's a pretty large file. I won't keep it on this fileshare for very long because it takes up so much space. The next release will include a full vocoder checkpoint with discriminators to help with finetuning.

https://drive.google.com/file/d/1AkRVg006R2Y8DnbTDkoYzY-xJ07WlZqM/view?usp=sharing

**Comment by bharaniyv** [comment]
Thank you very much for the checkpoint and I am looking for the next release
