### ISSUE TITLE
Can Toucan do voice conversion ?

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#84]
Hi,

First of all, thanks for this fresh update! Although Despite my careful look at ["Pre generated audio" section](https://github.com/DigitalPhonetics/IMS-Toucan#pre-generated-audios) I am still unsure to well understand what it's all about with "cloning style and voice". For me it sounds like Toucan is capable of voice conversion. But then while listening to the ["Poetry examples"](https://poetictts.github.io/) where it reads "synthesized" and the presence of `run_utterance_cloner.py` in the repo I would tend to consider it as voice cloning.

So how did the samples of the [prosody cloning section where made](https://toucanprosodycloningdemo.github.io/) and is Toucan capable of doing voice conversion (ie give an audio reference and it outputs the same message with a different voice) ?

Other than that I heard the multi language / multi speaker samples and was expecting to hear Italian / Spanish / Russian speakers rolling the "r"s while speaking French (ex : bonjourrrr, rrrouge, [surrr](https://youtu.be/9jKejdTMliE?t=40)) but this wasn't the case. So for me it does not sound the natural way an Italian speaker would speak French. 

Please note that I could not test the project yet since my GPU is still quite busy in the middle of training sessions :smiley: !

Looking forward to reading your explanations as always!

**Comment by Flux9665** [comment]
run_utterance_cloner is indeed a method of voice conversion, because it not only clones the voice, but also the prosody of the utterance. You just have to specify the text that is said during the voice conversion. 

The poetry samples showcase that the clone does not have to be one-to-one matching. You can clone an utterance and then modify the prosody and the speaker independently by modifying cloned values.

The accents in the multilingual part are not explicitly trained, they are just by-products of the language embeddings, which are needed for the multilingual training to work. So they are not really meant to perfectly encode an accent of a speaker. Nobody can say for sure which information is inside of those embeddings, because they are trained jointly with the TTS and don't have their own explicit objective function. It's just an observation, that for many cases the embedding and the accent of a speaker overlap,. But yeah, they are definitely not producing accents completely correctly, only to a certain extend. The big bottleneck is that an accent also changes which phonemes are produced. But the phonemes that the phonemizer produces for a text stay the same. Only their realization changes. And the rolled r is an entirely different phoneme from the one that the phonemizer produces for those cases. The language embedding only provides an offset, basically a flavour to the phoneme. Like someone with that mother tongue trying really hard to speak in the language of the text correctly.

**Comment by Ca-ressemble-a-du-fake** [comment]
Once again this becomes all cristal clear ! Thank you @Flux9665 I understand it now !
