### ISSUE TITLE
[run utterance cloner] What audio preprocessing can be applied to the reference audio  ?

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#92]
Hi, 

I tried run_utterance_cloner script with my voice as reference audio (16kHz mono) and it did not give good results although using another voice as reference audio (taken from the professional recording) was much better.

So I am wondering if there are some preprocessing I can do to the reference audio recorded from a smartphone recording app to improve the utterance cloning result ?

My voice sample was filtered from noise by software (ffmpeg afftdn with a noise floor of -25dB if that matters). I know this is nefarious for ASR because it removes some essential data from the waveform but I don't know if it should also be avoided for utterance cloning.

Looking forward to reading your reply!

**Comment by Flux9665** [comment]
The characteristics of the microphone are strongly reflected in the speaker embedding. So a microphone with little energy in the low frequencies, like a phone microphone, will often reflect in less high-quality samples. This is mostly because in the train data, a non-studio-quality microphone correlates with non-perfect recodring conditions. Also, getting a good speaker similarity without finetuning is difficult. Zero-shot works for the voice, but only very little for the speaking style, which is very important to the perceived similarity. That's something that this toolkit is not very good at, because I try to keep things simple and general. Here the focus is more on multilinguality.

**Comment by Ca-ressemble-a-du-fake** [comment]
I don't get the part about finetuning. Do you mean I should finetune the Meta model on several datasets from different speakers (including myself)? And then when running the utterance cloner with my voice as reference audio I should get better similarity ? But how to select another voice than mine, I can't find some kind of "speaker id" argument.

**Comment by Flux9665** [comment]
Yes, for ideal results you should finetune the TTS model on the speaker that you want to clone. And for selecting the voice, an audio reference of the speaker has to be given. I think you already know this from later issues, but I'm going through issues and answering old ones that I didn't get to :)

**Comment by Ca-ressemble-a-du-fake** [comment]
That's perfect to emphasize it again. It'll help others. Thank you.
